import type { Metadata } from 'next'
import { ModalsProvider } from '@mantine/modals'
import { Inter } from 'next/font/google'
import './globals.css'
import '@mantine/core/styles.css'

import { ColorSchemeScript, createTheme, MantineProvider } from '@mantine/core'
import { EbayProvider } from 'app/ebay/ebay-demo'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


const theme = createTheme({
  /* Put your mantine theme override here */
})

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <ColorSchemeScript />
    </head>
    <body>
    <MantineProvider forceColorScheme={'dark'}>
      <ModalsProvider>
        <EbayProvider>
          {children}
        </EbayProvider>
      </ModalsProvider>
    </MantineProvider>
    </body>
    </html>
  )
}
